language: objective-c

osx_image: xcode9
script:
- swift test -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.12" 
- travis_retry swift test -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.12" 
- bash <(curl -s https://codecov.io/bash)

notifications:
  slack: 'samedialabs:$SLACK_SAMEDIALABS_TRAVIS_CI'

